### ISSUE TITLE
Adapt newer command registration system (cleaner)

### ISSUE THREAD

**Issue by DieserMerlin** [Twasi/twasi-commands#5]

**Comment by Laraakaa** [comment]
We should probably list which plugins exactly are affected.

https://github.com/Twasi/example-plugin: Needs overall update (it's incredible how out of date this is.)
https://github.com/Twasi/twasi-giveaways: Update to new command system
https://github.com/Twasi/twasi-currency: Update to new command system
https://github.com/Twasi/twasi-commands: Update to new command system (funny how this is not changed yet :P )
https://github.com/Twasi/twasi-songrequest: We can skip it here since the plugin isn't finished. We just have to ensure that it's done by release.

**Comment by Laraakaa** [comment]
example-plugin was updated!

**Comment by DieserMerlin** [comment]
Twasi-commands uses the onMessage-function of the TwasiUserPlugin class. This will not be updated. All of the internal commands (!add, !del, !list, !setaccess) are using the newer system now.

https://github.com/Twasi/twasi-commands/commit/b7afbc3b9f67895c2ca8a5b1c19bf142c713ea2c
